pipeline {
    agent any
    environment {
        // AWS and ECR settings
        AWS_REGION    = "us-east-1" // Set your AWS region
        ECR_REPO      = "481202595277.dkr.ecr.us-east-1.amazonaws.com/us-population-fastapi"
        IMAGE_TAG     = "${env.BUILD_ID}"
        
        // ECS settings
        CLUSTER_NAME  = "your-ecs-cluster"
        SERVICE_NAME  = "your-ecs-service"
    }

    stages {
        stage('Stage 1') {
            steps {
                echo 'Hello world!'
                sh 'whoami'
            }
        }
	stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image locally; tag it with a temporary name
                    sh "docker build -t fastapi-app:${IMAGE_TAG} ."	
                }
            }
        }
	stage('Tag Docker Image') {
            steps {
                script {
                    // Tag the image with the ECR repository URI
                    sh "docker tag fastapi-app:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}"
                }
            }
        }
	stage('Login to ECR') {
            steps {
                script {
                    // Log in to Amazon ECR using the AWS CLI
                    sh """
                        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}
                    """
                }
            }
        }
        stage('Push Docker Image to ECR') {
            steps {
                script {
                    // Push the tagged image to ECR
                    sh "docker push ${ECR_REPO}:${IMAGE_TAG}"
                }
            }
        }
    }
}

