pipeline {
    agent any
    stages {
        stage('Stage 1') {
            steps {
                echo 'Hello world!'
                sh 'echo "Hello world from shell"'
            }
        }
	stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image locally; tag it with a temporary name
                    // sh "docker build -t fastapi-app:${IMAGE_TAG} ."	
                    sh "docker build -t us-population-fastapi-app:123 ."
                }
            }
        }
    }
}

